/**
 * Handles the creation and management of projects.
 */
(function() {
  'use strict';

  angular
    .module('LandApp')
    .factory('projectService', projectService);

  /** @ngInject */
  function projectService($q,
    firebaseReferenceService, messageService, olLayerGroupService, olUserLayerService, activeProjectService) {
    var service = {
      init: init,
      getProjectList: function() { return _projectList; },
      createProject: createProject,
      setProjectVisibility: setProjectVisibility,
      getActiveProject: getActiveProject,
      getBaseFarmProject: getBaseFarmProject
    };

    var _projectList = {};

    return service;

    /////////////////////////// PUBLIC ///////////////////////////

    /**
     * Initializes the service by loading project details from the db.
     */
    function init() {
      firebaseReferenceService
        .getUserProjectsRef()
        .on("value", function(projectList) {
          _projectList = {};

          if (projectList.exists()) {
            _projectList = projectList.val();

            angular.forEach(_projectList, function(value, key) {
              value.key = key;
            });

            var myFarm = getBaseFarmProject();
            myFarm.isActive = true;
            setProjectVisibility(myFarm);
          }
        });
    }

    /**
     * Toggles a project's visiblity.
     *
     * @param {Object} toggledProject Project to toggle
     */
    function setProjectVisibility(toggledProject) {
      if (toggledProject.key !== "myFarm") {
        // turn other project off
        angular.forEach(_projectList, function (project) {
          if (project.key !== "myFarm" && project.key !== toggledProject.key ) {
            project.isActive = false;
          }
        });
      }

      // active project is the current one, the farm or none
      var activeProjectKey = null;
      if (toggledProject.isActive) {
        activeProjectKey = toggledProject.key;
      }
      else if (_projectList.myFarm.isActive) {
        activeProjectKey = _projectList.myFarm.key;
      }
      activeProjectService.setActiveProjectKey(activeProjectKey);

      // show the ol group
      olLayerGroupService.toggleGroupVisibility(toggledProject.key, toggledProject.isActive);
    }

    /**
     * Returns the currently active project.
     * @return {Object} Project object
     */
    function getActiveProject() {
      return _projectList[activeProjectService.getActiveProjectKey()];
    }

    /**
     * Returns the base farm project.
     * @return {Object} Project object
     */
    function getBaseFarmProject() {
      return _projectList.myFarm;
    }

    /**
     * Creates a new named project.
     *
     * @param  {String}   projectName       Name of the new project
     * @param  {Bool}     isBaseFarmProject Whether this is a base farm project
     * @return {Promise}                    Promise object
     */
    function createProject(projectName, isBaseFarmProject) {
      var deferred = $q.defer();

      if (isBaseFarmProject && getBaseFarmProject()) {
        deferred.reject("A base farm layer already exists");
      } else {
        var project = {
          projectName: projectName
        };

        var projectListRef = firebaseReferenceService.getUserProjectsRef();

        // the base farm project has a static key (myFarm)
        // every other project has a random key generated by Firebase
        var projectRef = isBaseFarmProject ? firebaseReferenceService.getUserMyFarmRef() : projectListRef.push();

        // create layers and group for new project
        projectRef.set(project)
          .then(function() {
            project.key = projectRef.key();
            projectRef.once("value")
              .then(function(projectSnapshot) {
                olUserLayerService.createLayers(projectSnapshot);
                deferred.resolve(project);
              })
              .catch(function(error){
                deferred.reject(error);
                messageService.error(error);
              });
          })
          .catch(function(error) {
            deferred.reject(error);
            messageService.error(error);
          });
      }

      return deferred.promise;
    }
  }

})();
